workspace:
  base: /shark
  path: react-app

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    privileged: true
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:8.9.4
    commands:
      - yarn install

  rebuild-cache:
    image: drillster/drone-volume-cache
    privileged: true
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node:8.9.4
    commands:
      - npm build

  scp:
    image: appleboy/drone-scp
    host: 10.xx.xx.170
    username: root
    key_path: /root/.ssh/id_rsa
    #rm: true
    target:
     - /opt/react-app-build
    source:
     - build/*
