workspace:
  base: /shark
  path: react-app
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    privileged: true
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  install:
    image: node:8.9.4
    commands:
      - yarn install
  rebuild-cache:
    image: drillster/drone-volume-cache
    privileged: true
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node:8.9.4
    commands:
      - npm run build

  scp:
    image: appleboy/drone-scp
    host:
      - 207.148.89.26
    user: root
    secrets: [ ssh_password ]
    target: /opt/react-app-build
    source:
      - build/*
