workspace:
  base: /shark
  path: react-app

pipeline:
  init:
    image: docker
    environment:
      - DOCKER_HOST=tcp://104.238.149.14:8000
    commands:
      - docker --tls=false ps
  restore-cache:
    image: drillster/drone-volume-cache
    privileged: true
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:8.9.4
    commands:
      - yarn install

  rebuild-cache:
    image: drillster/drone-volume-cache
    privileged: true
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node:8.9.4
    commands:
      - npm build

services:
  docker:
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
+   privileged: true